version: '3'
services:
    api:
        build: .
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/usr/src/app
        ports:
            - 8000:8000
    db:
        image: postgres:11-alpine
        ports:
            - 5432:5432
